In [1]:
#import data
import pandas as pd
dataset = pd.read_csv('data.csv')
dataset.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [2]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Make               11914 non-null  object
 1   Model              11914 non-null  object
 2   Year               11914 non-null  int64
 3   Engine Fuel Type   11911 non-null  object
 4   Engine HP          11845 non-null  float64
 5   Engine Cylinders   11884 non-null  float64
 6   Transmission Type  11914 non-null  object
 7   Driven_Wheels      11914 non-null  object
 8   Number of Doors    11908 non-null  float64
 9   Market Category    8172 non-null   object
 10  Vehicle Size       11914 non-null  object
 11  Vehicle Style      11914 non-null  object
 12  highway MPG        11914 non-null  int64
 13  city mpg           11914 non-null  int64
 14  Popularity         11914 non-null  int64
 15  MSRP               11914 non-null  int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB

In [3]:
#One hot encoding Market Category
dataset['Market Category'] = dataset['Market Category'].fillna('Unknown')
dataset = pd.get_dummies(dataset, columns=['Market Category'])

In [4]:
#drop Market Category,Number of Doors, popularity
dataset.drop(['Number of Doors','Popularity'],axis=1,inplace=True)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 85 columns):
 #   Column                                                                  Non-Null Count  Dtype
---  ------                                                                  --------------  -----
 0   Make                                                                    11914 non-null  object
 1   Model                                                                   11914 non-null  object
 2   Year                                                                    11914 non-null  int64
 3   Engine Fuel Type                                                        11911 non-null  object
 4   Engine HP                                                               11845 non-null  float64
 5   Engine Cylinders                                                        11884 non-null  float64
 6   Transmission Type                                                       11914 non-null  object
 7   Driven_Wheels                                                           11914 non-null  object
 8   Vehicle Size                                                            11914 non-null  object
 9   Vehicle Style                                                           11914 non-null  object
 10  highway MPG                                                             11914 non-null  int64
 11  city mpg                                                                11914 non-null  int64
 12  MSRP                                                                    11914 non-null  int64
 13  Market Category_Crossover                                               11914 non-null  bool
 14  Market Category_Crossover,Diesel                                        11914 non-null  bool
 15  Market Category_Crossover,Exotic,Luxury,High-Performance                11914 non-null  bool
 16  Market Category_Crossover,Exotic,Luxury,Performance                     11914 non-null  bool
 17  Market Category_Crossover,Factory Tuner,Luxury,High-Performance         11914 non-null  bool
 18  Market Category_Crossover,Factory Tuner,Luxury,Performance              11914 non-null  bool
 19  Market Category_Crossover,Factory Tuner,Performance                     11914 non-null  bool
 20  Market Category_Crossover,Flex Fuel                                     11914 non-null  bool
 21  Market Category_Crossover,Flex Fuel,Luxury                              11914 non-null  bool
 22  Market Category_Crossover,Flex Fuel,Luxury,Performance                  11914 non-null  bool
 23  Market Category_Crossover,Flex Fuel,Performance                         11914 non-null  bool
 24  Market Category_Crossover,Hatchback                                     11914 non-null  bool
 25  Market Category_Crossover,Hatchback,Factory Tuner,Performance           11914 non-null  bool
 26  Market Category_Crossover,Hatchback,Luxury                              11914 non-null  bool
 27  Market Category_Crossover,Hatchback,Performance                         11914 non-null  bool
 28  Market Category_Crossover,Hybrid                                        11914 non-null  bool
 29  Market Category_Crossover,Luxury                                        11914 non-null  bool
 30  Market Category_Crossover,Luxury,Diesel                                 11914 non-null  bool
 31  Market Category_Crossover,Luxury,High-Performance                       11914 non-null  bool
 32  Market Category_Crossover,Luxury,Hybrid                                 11914 non-null  bool
 33  Market Category_Crossover,Luxury,Performance                            11914 non-null  bool
 34  Market Category_Crossover,Luxury,Performance,Hybrid                     11914 non-null  bool
 35  Market Category_Crossover,Performance                                   11914 non-null  bool
 36  Market Category_Diesel                                                  11914 non-null  bool
 37  Market Category_Diesel,Luxury                                           11914 non-null  bool
 38  Market Category_Exotic,Factory Tuner,High-Performance                   11914 non-null  bool
 39  Market Category_Exotic,Factory Tuner,Luxury,High-Performance            11914 non-null  bool
 40  Market Category_Exotic,Factory Tuner,Luxury,Performance                 11914 non-null  bool
 41  Market Category_Exotic,Flex Fuel,Factory Tuner,Luxury,High-Performance  11914 non-null  bool
 42  Market Category_Exotic,Flex Fuel,Luxury,High-Performance                11914 non-null  bool
 43  Market Category_Exotic,High-Performance                                 11914 non-null  bool
 44  Market Category_Exotic,Luxury                                           11914 non-null  bool
 45  Market Category_Exotic,Luxury,High-Performance                          11914 non-null  bool
 46  Market Category_Exotic,Luxury,High-Performance,Hybrid                   11914 non-null  bool
 47  Market Category_Exotic,Luxury,Performance                               11914 non-null  bool
 48  Market Category_Exotic,Performance                                      11914 non-null  bool
 49  Market Category_Factory Tuner,High-Performance                          11914 non-null  bool
 50  Market Category_Factory Tuner,Luxury                                    11914 non-null  bool
 51  Market Category_Factory Tuner,Luxury,High-Performance                   11914 non-null  bool
 52  Market Category_Factory Tuner,Luxury,Performance                        11914 non-null  bool
 53  Market Category_Factory Tuner,Performance                               11914 non-null  bool
 54  Market Category_Flex Fuel                                               11914 non-null  bool
 55  Market Category_Flex Fuel,Diesel                                        11914 non-null  bool
 56  Market Category_Flex Fuel,Factory Tuner,Luxury,High-Performance         11914 non-null  bool
 57  Market Category_Flex Fuel,Hybrid                                        11914 non-null  bool
 58  Market Category_Flex Fuel,Luxury                                        11914 non-null  bool
 59  Market Category_Flex Fuel,Luxury,High-Performance                       11914 non-null  bool
 60  Market Category_Flex Fuel,Luxury,Performance                            11914 non-null  bool
 61  Market Category_Flex Fuel,Performance                                   11914 non-null  bool
 62  Market Category_Flex Fuel,Performance,Hybrid                            11914 non-null  bool
 63  Market Category_Hatchback                                               11914 non-null  bool
 64  Market Category_Hatchback,Diesel                                        11914 non-null  bool
 65  Market Category_Hatchback,Factory Tuner,High-Performance                11914 non-null  bool
 66  Market Category_Hatchback,Factory Tuner,Luxury,Performance              11914 non-null  bool
 67  Market Category_Hatchback,Factory Tuner,Performance                     11914 non-null  bool
 68  Market Category_Hatchback,Flex Fuel                                     11914 non-null  bool
 69  Market Category_Hatchback,Hybrid                                        11914 non-null  bool
 70  Market Category_Hatchback,Luxury                                        11914 non-null  bool
 71  Market Category_Hatchback,Luxury,Hybrid                                 11914 non-null  bool
 72  Market Category_Hatchback,Luxury,Performance                            11914 non-null  bool
 73  Market Category_Hatchback,Performance                                   11914 non-null  bool
 74  Market Category_High-Performance                                        11914 non-null  bool
 75  Market Category_Hybrid                                                  11914 non-null  bool
 76  Market Category_Luxury                                                  11914 non-null  bool
 77  Market Category_Luxury,High-Performance                                 11914 non-null  bool
 78  Market Category_Luxury,High-Performance,Hybrid                          11914 non-null  bool
 79  Market Category_Luxury,Hybrid                                           11914 non-null  bool
 80  Market Category_Luxury,Performance                                      11914 non-null  bool
 81  Market Category_Luxury,Performance,Hybrid                               11914 non-null  bool
 82  Market Category_Performance                                             11914 non-null  bool
 83  Market Category_Performance,Hybrid                                      11914 non-null  bool
 84  Market Category_Unknown                                                 11914 non-null  bool
dtypes: bool(72), float64(2), int64(4), object(7)
memory usage: 2.0+ MB

In [6]:
#Normalize the numbers
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
numeric_columns = ['Year', 'Engine HP', 'Engine Cylinders', 'highway MPG', 'city mpg', 'MSRP']
dataset[numeric_columns] = scaler.fit_transform(dataset[numeric_columns])
dataset.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Vehicle Size,Vehicle Style,...,Market Category_Hybrid,Market Category_Luxury,"Market Category_Luxury,High-Performance","Market Category_Luxury,High-Performance,Hybrid","Market Category_Luxury,Hybrid","Market Category_Luxury,Performance","Market Category_Luxury,Performance,Hybrid",Market Category_Performance,"Market Category_Performance,Hybrid",Market Category_Unknown
0,BMW,1 Series M,0.777778,premium unleaded (required),0.295983,0.375,MANUAL,rear wheel drive,Compact,Coupe,...,False,False,False,False,False,False,False,False,False,False
1,BMW,1 Series,0.777778,premium unleaded (required),0.258985,0.375,MANUAL,rear wheel drive,Compact,Convertible,...,False,False,False,False,False,True,False,False,False,False
2,BMW,1 Series,0.777778,premium unleaded (required),0.258985,0.375,MANUAL,rear wheel drive,Compact,Coupe,...,False,False,True,False,False,False,False,False,False,False
3,BMW,1 Series,0.777778,premium unleaded (required),0.184989,0.375,MANUAL,rear wheel drive,Compact,Coupe,...,False,False,False,False,False,True,False,False,False,False
4,BMW,1 Series,0.777778,premium unleaded (required),0.184989,0.375,MANUAL,rear wheel drive,Compact,Convertible,...,False,True,False,False,False,False,False,False,False,False

In [7]:
categorical_cols = ['Make', 'Engine Fuel Type', 'Transmission Type', 'Driven_Wheels', 'Vehicle Size', 'Vehicle Style']
dataset = pd.get_dummies(dataset, columns=categorical_cols)

In [8]:
dataset.head()

,Model,Year,Engine HP,Engine Cylinders,highway MPG,city mpg,MSRP,Market Category_Crossover,"Market Category_Crossover,Diesel","Market Category_Crossover,Exotic,Luxury,High-Performance",...,Vehicle Style_Convertible,Vehicle Style_Convertible SUV,Vehicle Style_Coupe,Vehicle Style_Crew Cab Pickup,Vehicle Style_Extended Cab Pickup,Vehicle Style_Passenger Minivan,Vehicle Style_Passenger Van,Vehicle Style_Regular Cab Pickup,Vehicle Style_Sedan,Vehicle Style_Wagon
0,1 Series M,0.777778,0.295983,0.375,0.040936,0.092308,0.021384,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1,1 Series,0.777778,0.258985,0.375,0.046784,0.092308,0.018727,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,1 Series,0.777778,0.258985,0.375,0.046784,0.100000,0.016643,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,1 Series,0.777778,0.184989,0.375,0.046784,0.084615,0.013300,False,False,False,...,False,False,True,False,False,False,False,False,False,False
4,1 Series,0.777778,0.184989,0.375,0.046784,0.084615,0.015747,False,False,False,...,True,False,False,False,False,False,False,False,False,False

In [9]:
# Set the 'Model' column as the index so it's not included in the math
features_df = dataset.set_index('Model')

# Ensure all remaining data is numeric (convert those 'False'/'True' to 0/1 if they aren't already floats)
features_df = features_df.astype(float)

In [10]:
# 2. Fill missing numerical values with the median
numerical_cols_with_nans = ['Engine HP', 'Engine Cylinders'] 

for col in numerical_cols_with_nans:
    # Check if the column exists to avoid errors
    if col in dataset.columns:
        median_value = dataset[col].median()
        dataset[col] = dataset[col].fillna(median_value)

In [11]:
categorical_cols_with_nans = ['Engine Fuel Type', 'Number of Doors']

for col in categorical_cols_with_nans:
    if col in dataset.columns:
        # Get the most frequent value
        mode_value = dataset[col].mode()[0]
        dataset[col] = dataset[col].fillna(mode_value)

In [12]:
print(dataset.isnull().sum())

Model                               0
Year                                0
Engine HP                           0
Engine Cylinders                    0
highway MPG                         0
                                   ..
Vehicle Style_Passenger Minivan     0
Vehicle Style_Passenger Van         0
Vehicle Style_Regular Cab Pickup    0
Vehicle Style_Sedan                 0
Vehicle Style_Wagon                 0
Length: 165, dtype: int64

In [13]:
from sklearn.metrics.pairwise import cosine_similarity

# Calculate the similarity matrix for all cars against all cars
# This creates a massive grid where row i and column j is the similarity score between car i and car j
# Fill any remaining missing values before computing similarity
features_df = features_df.copy()
features_df = features_df.fillna(features_df.median(numeric_only=True)).astype(float)

cosine_sim_matrix = cosine_similarity(features_df)

In [14]:
indices = pd.Series(features_df.index)

In [15]:
def recommend_cars(model_name, cosine_sim=cosine_sim_matrix, top_n=5):
    # 1. Get the index of the target car
    idx = indices[indices == model_name].index[0]

    # 2. Get the similarity scores and sort them (highest to lowest)
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # NEW: Keep track of unique models we've found
    unique_recommendations = []
    seen_models = set()
    
    # 3. Loop through the scores
    for i in sim_scores:
        car_model = indices[i[0]] # Get the actual name of the car
        score = i[1]              # Get the similarity score
        
        # Check if it's NOT the car we searched for, AND we haven't recommended it yet
        if car_model != model_name and car_model not in seen_models:
            unique_recommendations.append((car_model, score))
            seen_models.add(car_model)
            
        # Stop once we have exactly top_n unique cars
        if len(unique_recommendations) == top_n:
            break
            
    return unique_recommendations

In [16]:
# Example 1: The Sports Car Enthusiast
print("Recommendations for a '1 Series M' (Compact, High HP, Coupe, Manual):")
print(recommend_cars('1 Series M'))

# Example 2: The Family Driver (Find a Minivan or large SUV in your dataset and test it)
print("Recommendations for a 'Odyssey':")
print(recommend_cars('Odyssey'))

# Example 3: The Commuter (Find an efficient sedan and test it)
print("Recommendations for a 'Corolla':")
print(recommend_cars('Corolla'))

Recommendations for a '1 Series M' (Compact, High HP, Coupe, Manual):
[('Z4 M', 0.9991955921161823), ('M2', 0.9980193289312715), ('M', 0.9978152628908951), ('M4', 0.8732387124230665), ('1 Series', 0.873080411700414)]
Recommendations for a 'Odyssey':
[('Ridgeline', 0.8766164771575802), ('Sienna', 0.876600430091339), ('Caravan', 0.8645358833805741), ('Grand Voyager', 0.8499332696733432), ('Accord', 0.7536433095867974)]
Recommendations for a 'Corolla':
[('Yaris iA', 0.9996005215683618), ('ECHO', 0.9916279902549248), ('Elantra', 0.8752470204831168), ('Forte', 0.8752469718584603), ('Versa', 0.8751846379453608)]

In [17]:

# Reload the original data only for displaying readable car specifications.
# The similarity matrix is still the one computed above.
original_specs = pd.read_csv('data.csv').reset_index().rename(columns={'index': 'row_id'})

spec_cols = [
    'row_id', 'Make', 'Model', 'Year', 'Vehicle Style', 'Vehicle Size',
    'Engine HP', 'Engine Cylinders', 'highway MPG', 'city mpg', 'MSRP'
]

# Create a readable unique label so cars with the same model name are not confused.
original_specs['car_label'] = original_specs.apply(
    lambda row: f"{row['row_id']}: {row['Make']} {row['Model']} ({row['Year']})",
    axis=1
)

print("Example car labels to use as unambiguous input:")
display(original_specs[['car_label', 'Vehicle Style', 'Vehicle Size', 'Engine HP', 'highway MPG', 'city mpg', 'MSRP']].head(10))

Example car labels to use as unambiguous input:

,car_label,Vehicle Style,Vehicle Size,Engine HP,highway MPG,city mpg,MSRP
0,0: BMW 1 Series M (2011),Coupe,Compact,335.0,26,19,46135
1,1: BMW 1 Series (2011),Convertible,Compact,300.0,28,19,40650
2,2: BMW 1 Series (2011),Coupe,Compact,300.0,28,20,36350
3,3: BMW 1 Series (2011),Coupe,Compact,230.0,28,18,29450
4,4: BMW 1 Series (2011),Convertible,Compact,230.0,28,18,34500
5,5: BMW 1 Series (2012),Coupe,Compact,230.0,28,18,31200
6,6: BMW 1 Series (2012),Convertible,Compact,300.0,26,17,44100
7,7: BMW 1 Series (2012),Coupe,Compact,300.0,28,20,39300
8,8: BMW 1 Series (2012),Convertible,Compact,230.0,28,18,36900
9,9: BMW 1 Series (2013),Convertible,Compact,230.0,27,18,37200

In [23]:

def find_car_rows(model_name, make=None, year=None, limit=10):
    # Find exact dataset rows for a model. This avoids ambiguity when many rows share the same model name.
    matches = original_specs['Model'].str.contains(model_name, case=False, na=False)
    if make is not None:
        matches &= original_specs['Make'].str.contains(make, case=False, na=False)
    if year is not None:
        matches &= original_specs['Year'].eq(year)
    return original_specs.loc[matches, ['car_label'] + spec_cols].head(limit)


def recommend_cars_with_specs(row_id, cosine_sim=cosine_sim_matrix, top_n=5):
    # Recommend similar cars using row_id instead of only model name.
    # This  uses the existing cosine similarity matrix from the previous cells.
    sim_scores = list(enumerate(cosine_sim[row_id]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    recommendations = []
    seen_models = set()
    target_model = original_specs.loc[row_id, 'Model']

    for candidate_row_id, score in sim_scores:
        if candidate_row_id == row_id:
            continue

        candidate_model = original_specs.loc[candidate_row_id, 'Model']
        if candidate_model == target_model or candidate_model in seen_models:
            continue

        seen_models.add(candidate_model)
        recommendations.append((candidate_row_id, score))

        if len(recommendations) == top_n:
            break

    result = original_specs.loc[[row for row, _ in recommendations], ['car_label'] + spec_cols].copy()
    result.insert(0, 'similarity', [score for _, score in recommendations])
    return result

print("Find possible rows for Honda Odyssey:")
display(find_car_rows('Odyssey', make='Honda', limit=5))

# Use one exact Odyssey row as input.
odyssey_row_id = int(find_car_rows('Odyssey', make='Honda', limit=5).iloc[3]['row_id'])
print(f"Recommendations for row {odyssey_row_id}:")
display(recommend_cars_with_specs(odyssey_row_id, top_n=5))

Find possible rows for Honda Odyssey:

,car_label,row_id,Make,Model,Year,Vehicle Style,Vehicle Size,Engine HP,Engine Cylinders,highway MPG,city mpg,MSRP
7293,7293: Honda Odyssey (2015),7293,Honda,Odyssey,2015,Passenger Minivan,Large,248.0,6.0,28,19,37775
7294,7294: Honda Odyssey (2015),7294,Honda,Odyssey,2015,Passenger Minivan,Large,248.0,6.0,28,19,35775
7295,7295: Honda Odyssey (2015),7295,Honda,Odyssey,2015,Passenger Minivan,Large,248.0,6.0,28,19,28975
7296,7296: Honda Odyssey (2015),7296,Honda,Odyssey,2015,Passenger Minivan,Large,248.0,6.0,28,19,37375
7297,7297: Honda Odyssey (2015),7297,Honda,Odyssey,2015,Passenger Minivan,Large,248.0,6.0,28,19,42030

Recommendations for row 7296:

,similarity,car_label,row_id,Make,Model,Year,Vehicle Style,Vehicle Size,Engine HP,Engine Cylinders,highway MPG,city mpg,MSRP
8501,0.876616,8501: Honda Ridgeline (2017),8501,Honda,Ridgeline,2017,Crew Cab Pickup,Large,280.0,6.0,26,19,35930
9240,0.876600,9240: Toyota Sienna (2017),9240,Toyota,Sienna,2017,Passenger Minivan,Large,296.0,6.0,27,19,42800
2335,0.864536,2335: Dodge Caravan (2006),2335,Dodge,Caravan,2006,Passenger Minivan,Large,180.0,6.0,24,17,22520
5538,0.849934,5538: Plymouth Grand Voyager (2000),5538,Plymouth,Grand Voyager,2000,Passenger Minivan,Large,158.0,6.0,23,16,2267
1265,0.753643,1265: Honda Accord (2017),1265,Honda,Accord,2017,Sedan,Midsize,278.0,6.0,33,21,32895

In [25]:

def evaluate_recommender(test_row_ids, top_n=5):
    # Simple evaluation: check whether recommendations share style/size and have similar specs.
    rows = []
    for row_id in test_row_ids:
        target = original_specs.loc[row_id]
        recs = recommend_cars_with_specs(row_id, top_n=top_n)

        rows.append({
            'input_car': target['car_label'],
            'same_vehicle_style_rate': (recs['Vehicle Style'] == target['Vehicle Style']).mean(),
            'same_vehicle_size_rate': (recs['Vehicle Size'] == target['Vehicle Size']).mean(),
            'avg_price_difference': (recs['MSRP'] - target['MSRP']).abs().mean(),
            'avg_hp_difference': (recs['Engine HP'] - target['Engine HP']).abs().mean(),
            'avg_highway_mpg_difference': (recs['highway MPG'] - target['highway MPG']).abs().mean(),
            'avg_city_mpg_difference': (recs['city mpg'] - target['city mpg']).abs().mean(),
            'avg_similarity': recs['similarity'].mean(),
        })

    return pd.DataFrame(rows)

# Five example cars for evaluation.
test_row_ids = [
    int(find_car_rows('Odyssey', make='Honda', limit=2).iloc[1]['row_id']),
    int(find_car_rows('Corolla', make='Toyota', limit=1).iloc[0]['row_id']),
    int(find_car_rows('Mustang', make='Ford', limit=1).iloc[0]['row_id']),
    int(find_car_rows('F-150', make='Ford', limit=1).iloc[0]['row_id']),
    int(find_car_rows('911', make='Porsche', limit=1).iloc[0]['row_id']),
]

evaluation_table = evaluate_recommender(test_row_ids, top_n=5)
display(evaluation_table)

print("Average evaluation scores:")
display(evaluation_table.drop(columns=['input_car']).mean().to_frame('average'))

,input_car,same_vehicle_style_rate,same_vehicle_size_rate,avg_price_difference,avg_hp_difference,avg_highway_mpg_difference,avg_city_mpg_difference,avg_similarity
0,7294: Honda Odyssey (2015),0.6,0.8,10970.6,53.6,3.4,1.4,0.844266
1,2922: Toyota Corolla iM (2017),1.0,1.0,1277.0,12.0,2.2,1.6,0.925655
2,7064: Ford Mustang SVT Cobra (1997),0.8,1.0,7882.6,64.6,1.2,1.2,0.724129
3,4447: Ford F-150 Heritage (2004),1.0,0.8,15317.4,13.0,1.6,1.0,0.888732
4,920: Porsche 911 (2015),0.6,1.0,32160.0,22.0,1.2,0.4,0.900713

Average evaluation scores:

                                 average
same_vehicle_style_rate         0.800000
same_vehicle_size_rate          0.920000
avg_price_difference        13521.520000
avg_hp_difference              33.040000
avg_highway_mpg_difference      1.920000
avg_city_mpg_difference         1.120000
avg_similarity                  0.856699